name: Checks

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.0'
      - name: Run checks with make
        run: make check
